[package]
name = "raggedy-bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
strip = "symbols"
codegen-units = 1

[target.'cfg(target_arch = "x86_64")']
linker = "ld"
