[build]
target = "x86_64-bootloader.json"

[unstable]
build-std = ["core"]

[target.x86_64-bootloader]
rustflags = [
    "-C", "link-arg=-Tboot.ld",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static",
    "-C", "link-arg=-no-pie",
    "-C", "relocation-model=static"
]
